name: 'Test'
on:
  pull_request:
    types: [closed]
    branches: [develop, qa, uat, master]
  workflow_dispatch:

jobs:
  Test-build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: dev build & deploy
      if: github.event.pull_request.merged == true && github.base_ref == 'develop'
      run: |
            echo "DEV"
    
    - name: qa build & deploy
      if: github.event.pull_request.merged == true && github.base_ref == 'qa'
      run: |
            echo "QA"

    - name: uat build & deploy
      if: github.event.pull_request.merged == true && github.base_ref == 'uat'
      run: |
            echo "UAT"
    
    - name: prod build & deploy
      if: github.event.pull_request.merged == true && github.base_ref == 'main'
      run: |
            echo "PROD"
